name: Build

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    # 允许手动触发工作流
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Upload artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: dist
                  path: build/dist
                  retention-days: 7
